### ISSUE TITLE
This package causes the server-side function to be undefined

### ISSUE THREAD

**Issue by MauriceZ** [djedi23/meteor-sanitize-html-client#1]
If [meteor-sanitize-html](https://github.com/djedi23/meteor-sanitize-html) is installed and I install this package, the server-side function is undefined

**Comment by djedi23** [comment]
Hello, 

I reproduced the bug.
I forgot to restrict the export to the client.

I just updated atmosphere with the corrected version 1.10.0_1.
Please let me know if it correct the bug in your code.

I used this scenario to reproduced it:

``` sh
meteor create test-sanitize
cd test-sanitize
meteor add djedi:sanitize-html@1.10.0
meteor add djedi:sanitize-html-client@1.10.0
```

I modified the js file:

``` js
if (Meteor.isClient) {
  // counter starts at 0
  Session.setDefault('counter', 0);

  Template.hello.helpers({
    counter: function () {
      return sanitizeHtml("some </table><b>bad</b> html"); // <<<< CLIENT TEST IS HERE
    }
  });

  Template.hello.events({
    'click button': function () {
      // increment the counter when button is clicked
      Session.set('counter', Session.get('counter') + 1);
    }
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    // code to run on server at startup
    console.log(sanitizeHtml("some </table><b>bad</b> html")); // <<<<< SERVER TEST IS HERE
  });
}
```

**Comment by dpatte** [comment]
i also have this issue.
Do I need too add both djedi:sanitize-html (1.6.1)
and djedi:sanitize-html-client (1.10.1)?

**Comment by djedi23** [comment]
I just redo the test with the versions djedi:sanitize-html@1.10.1 and djedi:sanitize-html-client@1.10.1 and I didn't reproduce the bug.

I recommend to updrade to djedi:sanitize-html@1.10.1 and djedi:sanitize-html-client@1.10.1 .

NB: If you need to sanitize html both in client and server side, you need to install two packages djedi:sanitize-html (server side) and djedi:sanitize-html-client (client side).
